remote_theme: pmarsceill/just-the-docs@v0.3.3
logo: "/assets/marco-betschart.png"
search_enabled: true
aux_links_new_tab: true
aux_links:
  "Twitter":
    - "//twitter.com/marbetschar"

collections:
  areas:
    permalink: "/:collection/:path/"
    output: true
  docs:
    permalink: "/:collection/:path"
    output: true
  projects:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    areas:
      name: Areas
    projects:
      name: Projects