remote_theme: pmarsceill/just-the-docs
logo: "/assets/marco-betschart.png"
search_enabled: true
aux_links_new_tab: true
aux_links:
  "Twitter":
    - "//twitter.com/marbetschar"

collections:
  projects:
    permalink: "/:collection/:path/"
    output: true
  areas:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    projects:
      name: Projects
    areas:
      name: Areas
