remote_theme: cotes2020/jekyll-theme-chirpy
title: Marco Betschart
author: Marco Betschart
github:
  username: marbetschar
twitter:
  username: marbetschar
social:
  name: Marco Betschart
  email: contact@marco.betschart.name
theme_mode: dark